/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package utfpr.http;

import java.awt.Component;
import java.util.ArrayList;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;

/**
 *
 * @author User
 */
public class Tela1 extends javax.swing.JFrame {
    ArrayList <Estados> estados_brasil = new ArrayList(); //Lista dos estados que uma vez que for feito a busca, todas os métodos podem usar sem ter que 
    //procurar novamente
    ArrayList <Municipio> municipios_estado = new ArrayList();//Mesma ideia para os múnicipios
    DefaultListModel modeloListaMunicipios = new DefaultListModel();//Essencial para poder usar a List
  
    public Tela1() {
        initComponents();
        this.istMunicipios.setModel(modeloListaMunicipios);//Iniciar a lista
    }
    public void carregarLista(int id){ // Função para pegar o ID do munipio selecionado e carregar na lista
        JsonToObjetos carregar = new JsonToObjetos();
        municipios_estado = carregar.buscarMunicipio(id);
        for(int i = 0; i<municipios_estado.size(); i++){
            Municipio temp = municipios_estado.get(i);
            modeloListaMunicipios.addElement(temp);
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DetalheMunicipio.class.getName());
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        bntProcurar = new javax.swing.JButton();
        txtEstado = new javax.swing.JLabel();
        cmbEstados = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        istMunicipios = new javax.swing.JList<>();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscador de Estado 2000");
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.setToolTipText("");

        bntProcurar.setBackground(new java.awt.Color(153, 255, 204));
        bntProcurar.setForeground(new java.awt.Color(0, 0, 0));
        bntProcurar.setText("Procurar pelos estados");
        bntProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntProcurarActionPerformed(evt);
            }
        });

        txtEstado.setBackground(new java.awt.Color(204, 204, 255));
        txtEstado.setForeground(new java.awt.Color(0, 0, 0));
        txtEstado.setText("Selecione o estado desejado");

        cmbEstados.setBackground(new java.awt.Color(153, 255, 204));
        cmbEstados.setForeground(new java.awt.Color(0, 0, 0));
        cmbEstados.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbEstadosItemStateChanged(evt);
            }
        });
        cmbEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(82, Short.MAX_VALUE)
                        .addComponent(bntProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(bntProcurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        istMunicipios.setBackground(new java.awt.Color(153, 255, 204));
        istMunicipios.setForeground(new java.awt.Color(0, 0, 0));
        istMunicipios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                istMunicipiosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(istMunicipios);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadosActionPerformed
        modeloListaMunicipios.removeAllElements();//Importante pois sem limpar a lista não adiciona os novos elementos
        int idx_atual = this.cmbEstados.getSelectedIndex();//Pega o indice do objeto atual do combobox
        int idEstadoAtual = estados_brasil.get(idx_atual).getId();//Pega o indice da lista onde os estados estão, para conseguir verificar qual estado está selecionado
        carregarLista(idEstadoAtual);//E por fim, com o id carrega alista
    }//GEN-LAST:event_cmbEstadosActionPerformed

    private void bntProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntProcurarActionPerformed
        JsonToObjetos procurar = new JsonToObjetos(); //Inicia o objeto da classe onde foi feito os métodos para acessar estados/Municipios da API
        estados_brasil = procurar.buscarEstados();//Essa função retorna uma lista, o que o estado_brasil está fazendo é recebendo o endereço onde aponta para a lista
         for(int i = 0; i<estados_brasil.size(); i++){
           Estados temp = estados_brasil.get(i);//Adicionando todos os estados no comboBOX
        this.cmbEstados.addItem(temp);
       }
    }//GEN-LAST:event_bntProcurarActionPerformed

    private void cmbEstadosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbEstadosItemStateChanged
     //Não sei remover :(
    }//GEN-LAST:event_cmbEstadosItemStateChanged

    private void istMunicipiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_istMunicipiosMouseClicked
        if(evt.getClickCount() == 2){//Se o usuario der 2 cliques na lista
        Municipio atual = (Municipio) modeloListaMunicipios.getElementAt(istMunicipios.getSelectedIndex());//Verifica qual foi o municipio clicado
        //E retorna o index do municipio
        
        DetalheMunicipio janelaMunicipio = new DetalheMunicipio(this, false); //"disponibiliza" a segunda tela. Deixei como não modal porque se quiser acessar dois
        //Municipios de uma vez tudo bem
        janelaMunicipio.setLocationRelativeTo(this);//Para a janela aparecer "em cima" da tela principal, pensei que somente com o "this" seria suficiente mas não estava indo
        String nome_atual = atual.getNome();//Passa o nome do municipio para uma variavel
        String id_atual = String.valueOf(atual.getId());//Passa o id do munipio para uma variavel, depois de fazer o value of para string
        String Uf_atual = atual.getSigla();//Passa a sigla(UF) para uma variavel
        String regiao_atual = atual.getRegiao();//Passa a região para uma variavel
        
        janelaMunicipio.setTxtNome(nome_atual);//Preencher com seus respectivos 
        janelaMunicipio.setTxtID(id_atual);
        janelaMunicipio.setTxtRegiao(regiao_atual);
        janelaMunicipio.setTxtUF(Uf_atual);
        
        
        janelaMunicipio.setVisible(true);
        }
    }//GEN-LAST:event_istMunicipiosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tela1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntProcurar;
    private javax.swing.JComboBox<Estados> cmbEstados;
    private javax.swing.JList<String> istMunicipios;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txtEstado;
    // End of variables declaration//GEN-END:variables
}
